insert into public.quotes (text, author, source) values
-- Marcus Aurelius — simple, direct
('You have power over your mind, not outside events.', 'Marcus Aurelius', 'Meditations'),
('The happiness of your life depends on the quality of your thoughts.', 'Marcus Aurelius', 'Meditations'),
('Waste no more time arguing about what a good person should be. Be one.', 'Marcus Aurelius', 'Meditations'),
('When you wake up, think about what a gift it is to be alive.', 'Marcus Aurelius', 'Meditations'),
('Very little is needed to make a happy life.', 'Marcus Aurelius', 'Meditations'),
('Accept what you cannot change. Love the people life gives you.', 'Marcus Aurelius', 'Meditations'),
('Look inside yourself. That is where your strength is.', 'Marcus Aurelius', 'Meditations'),
('The best answer to anger is silence.', 'Marcus Aurelius', 'Meditations'),
('Do not fear death. Fear never having truly lived.', 'Marcus Aurelius', 'Meditations'),
('Be kind to yourself. Be strict with yourself.', 'Marcus Aurelius', 'Meditations'),
('Watch the stars and see yourself among them.', 'Marcus Aurelius', 'Meditations'),
('If it is not right, do not do it. If it is not true, do not say it.', 'Marcus Aurelius', 'Meditations'),
('Everything changes. That is the nature of things.', 'Marcus Aurelius', 'Meditations'),
('Each day provides its own gifts.', 'Marcus Aurelius', 'Meditations'),
('What stands in the way becomes the way.', 'Marcus Aurelius', 'Meditations'),
('Stay in the present moment.', 'Marcus Aurelius', 'Meditations'),
('You always have the option of having no opinion.', 'Marcus Aurelius', 'Meditations'),
('Do every act as if it were your last.', 'Marcus Aurelius', 'Meditations'),
('Everything that happens is meant to happen.', 'Marcus Aurelius', 'Meditations'),
('Start fresh right now, in this moment.', 'Marcus Aurelius', 'Meditations'),
('We love ourselves most but care more about others'' opinions.', 'Marcus Aurelius', 'Meditations'),
('Keep an untroubled spirit. See things for what they are.', 'Marcus Aurelius', 'Meditations'),
('Nowhere is there more peace than inside your own mind.', 'Marcus Aurelius', 'Meditations'),
('Choose not to be harmed, and you will not feel harmed.', 'Marcus Aurelius', 'Meditations'),
('Let go with grace. Receive with gratitude.', 'Marcus Aurelius', 'Meditations'),
('The obstacle is the path.', 'Marcus Aurelius', 'Meditations'),
('To be calm is the highest achievement.', 'Marcus Aurelius', 'Meditations'),
('Be grateful for what you have instead of wishing for what you do not.', 'Marcus Aurelius', 'Meditations'),
('Loss is just another word for change.', 'Marcus Aurelius', 'Meditations'),
('The universe is change. Life is what you think it is.', 'Marcus Aurelius', 'Meditations'),

-- Epictetus — simple, direct
('It is not what happens to you, but how you respond that matters.', 'Epictetus', 'Enchiridion'),
('We suffer more in our imagination than in reality.', 'Epictetus', 'Discourses'),
('First decide who you want to be. Then do what you need to do.', 'Epictetus', 'Discourses'),
('Happiness comes from letting go of what you cannot control.', 'Epictetus', 'Enchiridion'),
('If someone can laugh at themselves, they never run out of joy.', 'Epictetus', 'Discourses'),
('Freedom comes from letting go of what is not up to you.', 'Epictetus', 'Discourses'),
('No one can make you feel anything without your permission.', 'Epictetus', 'Enchiridion'),
('Do not explain your philosophy. Live it.', 'Epictetus', 'Enchiridion'),
('You become what you repeatedly do.', 'Epictetus', 'Discourses'),
('Only worry about what is in your control.', 'Epictetus', 'Enchiridion'),
('Difficulty shows what people are made of.', 'Epictetus', 'Discourses'),
('Be careful who you spend your time with. It shapes who you are.', 'Epictetus', 'Discourses'),
('Do not wish things were easier. Wish you were better.', 'Epictetus', 'Discourses'),
('Progress comes from practice, not from talking about it.', 'Epictetus', 'Discourses'),
('Make the best use of what is in your power.', 'Epictetus', 'Enchiridion'),
('If you want to improve, be okay with looking foolish at first.', 'Epictetus', 'Enchiridion'),
('Every moment is a fresh beginning.', 'Epictetus', 'Discourses'),
('What upsets you is not what happened but your thoughts about it.', 'Epictetus', 'Enchiridion'),
('True freedom is wanting what you already have.', 'Epictetus', 'Discourses'),
('Small steps every day lead to big change.', 'Epictetus', 'Discourses'),

-- Seneca — simple, direct
('Luck is what happens when preparation meets opportunity.', 'Seneca', 'Letters'),
('It is not that we have a short time to live, but that we waste much of it.', 'Seneca', 'On the Shortness of Life'),
('Begin at once to live.', 'Seneca', 'On the Shortness of Life'),
('The whole future lies in uncertainty. Live right now.', 'Seneca', 'Letters'),
('Sometimes even to live is an act of courage.', 'Seneca', 'Letters'),
('True happiness is to enjoy the present without worrying about the future.', 'Seneca', 'Letters'),
('We are more often frightened than hurt.', 'Seneca', 'Letters'),
('Difficulties make you stronger if you let them.', 'Seneca', 'Letters'),
('You learn more about someone in an hour of play than in a year of talk.', 'Seneca', 'Letters'),
('Hang on to your youthful enthusiasm. You will be able to use it better as you get older.', 'Seneca', 'Letters'),
('Every new beginning comes from some other beginning''s end.', 'Seneca', 'Letters'),
('As long as you live, keep learning how to live.', 'Seneca', 'Letters'),
('The greatest wealth is a peaceful mind.', 'Seneca', 'Letters'),
('Associate with people who are likely to improve you.', 'Seneca', 'Letters'),
('If you really want to escape what bothers you, you need to change yourself, not your location.', 'Seneca', 'Letters'),
('Throw me to the wolves and I will come back leading the pack.', 'Seneca', 'Letters'),
('The mind that is anxious about the future is miserable.', 'Seneca', 'Letters'),
('A gem cannot be polished without friction.', 'Seneca', 'Letters'),
('While we wait for life, life passes.', 'Seneca', 'On the Shortness of Life'),
('No one is crushed by misfortune unless they were first deceived by comfort.', 'Seneca', 'Letters'),

-- Lao Tzu
('A journey of a thousand miles begins with a single step.', 'Lao Tzu', 'Tao Te Ching'),
('Nature does not hurry, yet everything is accomplished.', 'Lao Tzu', 'Tao Te Ching'),
('Be content with what you have. Rejoice in the way things are.', 'Lao Tzu', 'Tao Te Ching'),
('The best time to plant a tree was twenty years ago. The second best time is now.', 'Lao Tzu', 'Tao Te Ching'),
('Silence is a source of great strength.', 'Lao Tzu', 'Tao Te Ching'),
('When you let go of what you are, you become what you might be.', 'Lao Tzu', 'Tao Te Ching'),
('Knowing others is intelligence. Knowing yourself is true wisdom.', 'Lao Tzu', 'Tao Te Ching'),
('Simplicity is the ultimate sophistication.', 'Lao Tzu', 'Tao Te Ching'),
('Stop leaving and you will arrive. Stop searching and you will see.', 'Lao Tzu', 'Tao Te Ching'),
('Water is soft and patient but it carves through rock.', 'Lao Tzu', 'Tao Te Ching'),

-- Thich Nhat Hanh
('Smile, breathe, and go slowly.', 'Thich Nhat Hanh', NULL),
('The present moment is the only moment available to us.', 'Thich Nhat Hanh', NULL),
('Peace in oneself, peace in the world.', 'Thich Nhat Hanh', NULL),
('Breathing in, I calm my body. Breathing out, I smile.', 'Thich Nhat Hanh', NULL),
('Walk as if you are kissing the Earth with your feet.', 'Thich Nhat Hanh', NULL),
('Sometimes your joy is the source of your smile, and sometimes your smile is the source of your joy.', 'Thich Nhat Hanh', NULL),
('Drink your tea slowly. This is your time.', 'Thich Nhat Hanh', NULL),
('There is no way to happiness. Happiness is the way.', 'Thich Nhat Hanh', NULL),
('You are enough just as you are.', 'Thich Nhat Hanh', NULL),
('Let go of worrying. Let go of fear.', 'Thich Nhat Hanh', NULL),

-- Other wisdom
('Be yourself. Everyone else is already taken.', 'Oscar Wilde', NULL),
('Calm mind brings inner strength and self-confidence.', 'Dalai Lama', NULL),
('Do what you can, with what you have, where you are.', 'Theodore Roosevelt', NULL),
('Be the change you wish to see in the world.', 'Mahatma Gandhi', NULL),
('The only way to do great work is to love what you do.', 'Steve Jobs', NULL),
('In the middle of difficulty lies opportunity.', 'Albert Einstein', NULL),
('What you think, you become.', 'Buddha', NULL),
('All we have to decide is what to do with the time that is given us.', 'J.R.R. Tolkien', NULL),
('The wound is the place where the light enters you.', 'Rumi', NULL),
('Yesterday is gone. Tomorrow is not promised. Today is a gift.', 'Eleanor Roosevelt', NULL);
