insert into public.quotes (text, author, source) values
-- Marcus Aurelius (~40 quotes)
('You have power over your mind, not outside events. Realize this, and you will find strength.', 'Marcus Aurelius', 'Meditations'),
('The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius', 'Meditations'),
('Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius', 'Meditations'),
('Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius', 'Meditations'),
('When you arise in the morning, think of what a precious privilege it is to be alive.', 'Marcus Aurelius', 'Meditations'),
('The soul becomes dyed with the color of its thoughts.', 'Marcus Aurelius', 'Meditations'),
('Accept the things to which fate binds you, and love the people with whom fate brings you together.', 'Marcus Aurelius', 'Meditations'),
('Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.', 'Marcus Aurelius', 'Meditations'),
('It is not death that a man should fear, but he should fear never beginning to live.', 'Marcus Aurelius', 'Meditations'),
('Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.', 'Marcus Aurelius', 'Meditations'),
('The best revenge is not to be like your enemy.', 'Marcus Aurelius', 'Meditations'),
('Dwell on the beauty of life. Watch the stars, and see yourself running with them.', 'Marcus Aurelius', 'Meditations'),
('Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.', 'Marcus Aurelius', 'Meditations'),
('If it is not right, do not do it. If it is not true, do not say it.', 'Marcus Aurelius', 'Meditations'),
('The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.', 'Marcus Aurelius', 'Meditations'),
('How much more grievous are the consequences of anger than the causes of it.', 'Marcus Aurelius', 'Meditations'),
('To be calm is the highest achievement of the self.', 'Marcus Aurelius', 'Meditations'),
('Loss is nothing else but change, and change is nature''s delight.', 'Marcus Aurelius', 'Meditations'),
('Be tolerant with others and strict with yourself.', 'Marcus Aurelius', 'Meditations'),
('Do not indulge in dreams of having what you have not, but reckon up the chief of the blessings you do possess.', 'Marcus Aurelius', 'Meditations'),
('The universe is change; our life is what our thoughts make it.', 'Marcus Aurelius', 'Meditations'),
('Each day provides its own gifts.', 'Marcus Aurelius', 'Meditations'),
('Begin each day by telling yourself: today I shall meet with interference, ingratitude, and insolence. But I shall not be disturbed.', 'Marcus Aurelius', 'Meditations'),
('What stands in the way becomes the way.', 'Marcus Aurelius', 'Meditations'),
('Confine yourself to the present.', 'Marcus Aurelius', 'Meditations'),
('Nowhere can man find a quieter or more untroubled retreat than in his own soul.', 'Marcus Aurelius', 'Meditations'),
('You always own the option of having no opinion.', 'Marcus Aurelius', 'Meditations'),
('Do every act of your life as though it were the very last act of your life.', 'Marcus Aurelius', 'Meditations'),
('Everything that happens, happens as it should.', 'Marcus Aurelius', 'Meditations'),
('He who lives in harmony with himself lives in harmony with the universe.', 'Marcus Aurelius', 'Meditations'),
('Think of the life you have lived until now as over. Start a new one from this moment.', 'Marcus Aurelius', 'Meditations'),
('It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinion than our own.', 'Marcus Aurelius', 'Meditations'),
('The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.', 'Marcus Aurelius', 'Meditations'),
('To live a good life: we have the potential for it. If we learn to be indifferent to what makes no difference.', 'Marcus Aurelius', 'Meditations'),
('No man is free who is not master of himself.', 'Marcus Aurelius', 'Meditations'),
('When another blames you or hates you, go to their souls and see what sort of people they are. You will not be troubled.', 'Marcus Aurelius', 'Meditations'),
('The present moment is all you ever have.', 'Marcus Aurelius', 'Meditations'),
('Choose not to be harmed, and you won''t feel harmed. Don''t feel harmed, and you haven''t been.', 'Marcus Aurelius', 'Meditations'),
('The impediment to action advances action. What stands in the way becomes the way.', 'Marcus Aurelius', 'Meditations'),
('Receive without conceit, release without struggle.', 'Marcus Aurelius', 'Meditations'),

-- Epictetus (~30 quotes)
('It''s not what happens to you, but how you react to it that matters.', 'Epictetus', 'Enchiridion'),
('Man is not worried by real problems so much as by his imagined anxieties about real problems.', 'Epictetus', 'Discourses'),
('First say to yourself what you would be; and then do what you have to do.', 'Epictetus', 'Discourses'),
('There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.', 'Epictetus', 'Enchiridion'),
('He who laughs at himself never runs out of things to laugh at.', 'Epictetus', 'Discourses'),
('Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.', 'Epictetus', 'Discourses'),
('Wealth consists not in having great possessions, but in having few wants.', 'Epictetus', 'Discourses'),
('Don''t explain your philosophy. Embody it.', 'Epictetus', 'Enchiridion'),
('No great thing is created suddenly, any more than a bunch of grapes or a fig.', 'Epictetus', 'Discourses'),
('If you want to improve, be content to be thought foolish and stupid.', 'Epictetus', 'Enchiridion'),
('Make the best use of what is in your power, and take the rest as it happens.', 'Epictetus', 'Discourses'),
('Circumstances don''t make the man, they only reveal him to himself.', 'Epictetus', 'Discourses'),
('Other people''s views and troubles can be contagious. Don''t sabotage yourself by unwittingly adopting them.', 'Epictetus', 'Enchiridion'),
('Any person capable of angering you becomes your master.', 'Epictetus', 'Discourses'),
('We cannot choose our external circumstances, but we can always choose how we respond to them.', 'Epictetus', 'Enchiridion'),
('Caretake this moment. Immerse yourself in its particulars.', 'Epictetus', 'Discourses'),
('Seek not the good in external things; seek it in yourselves.', 'Epictetus', 'Discourses'),
('It is difficulties that show what men are.', 'Epictetus', 'Discourses'),
('Keep your attention focused entirely on what is truly your own concern, and be clear that what belongs to others is their business.', 'Epictetus', 'Enchiridion'),
('People are not disturbed by things, but by the views they take of them.', 'Epictetus', 'Enchiridion'),
('The key is to keep company only with people who uplift you, whose presence calls forth your best.', 'Epictetus', 'Discourses'),
('He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.', 'Epictetus', 'Enchiridion'),
('Attach yourself to what is spiritually superior, regardless of what other people think or do.', 'Epictetus', 'Enchiridion'),
('Know, first, who you are, and then adorn yourself accordingly.', 'Epictetus', 'Discourses'),
('On the occasion of every accident that befalls you, remember to turn to yourself and inquire what power you have to turn it to use.', 'Epictetus', 'Enchiridion'),
('Small-minded people blame others. Average people blame themselves. The wise see all blame as foolishness.', 'Epictetus', 'Enchiridion'),
('Permit nothing to cleave to you that is not your own; nothing to grow to you that may give you agony when it is torn away.', 'Epictetus', 'Discourses'),
('Nature hath given men one tongue but two ears, that we may hear from others twice as much as we speak.', 'Epictetus', 'Discourses'),
('Only the educated are free.', 'Epictetus', 'Discourses'),
('Practice yourself in little things, and thence proceed to greater.', 'Epictetus', 'Discourses'),

-- Seneca (~30 quotes)
('We suffer more often in imagination than in reality.', 'Seneca', 'Letters'),
('Luck is what happens when preparation meets opportunity.', 'Seneca', 'Letters'),
('Begin at once to live, and count each separate day as a separate life.', 'Seneca', 'Letters'),
('It is not that we have a short time to live, but that we waste a great deal of it.', 'Seneca', 'On the Shortness of Life'),
('True happiness is to enjoy the present, without anxious dependence upon the future.', 'Seneca', 'Letters'),
('Difficulties strengthen the mind, as labor does the body.', 'Seneca', 'Letters'),
('While we wait for life, life passes.', 'Seneca', 'On the Shortness of Life'),
('He who is brave is free.', 'Seneca', 'Letters'),
('As is a tale, so is life: not how long it is, but how good it is, is what matters.', 'Seneca', 'Letters'),
('Sometimes even to live is an act of courage.', 'Seneca', 'Letters'),
('If a man knows not to which port he sails, no wind is favorable.', 'Seneca', 'Letters'),
('A gem cannot be polished without friction, nor a man perfected without trials.', 'Seneca', 'Letters'),
('Nothing is more honorable than a grateful heart.', 'Seneca', 'Letters'),
('We are more often frightened than hurt; and we suffer more from imagination than from reality.', 'Seneca', 'Letters'),
('Hang on to your youthful enthusiasms; you''ll be able to use them better when you are older.', 'Seneca', 'Letters'),
('Life is long, if you know how to use it.', 'Seneca', 'On the Shortness of Life'),
('Wherever there is a human being, there is an opportunity for kindness.', 'Seneca', 'Letters'),
('The whole future lies in uncertainty: live immediately.', 'Seneca', 'On the Shortness of Life'),
('Associate with those who will make a better man of you.', 'Seneca', 'Letters'),
('He suffers more than necessary, who suffers before it is necessary.', 'Seneca', 'Letters'),
('The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.', 'Seneca', 'On the Shortness of Life'),
('No person has the power to have everything they want, but it is in their power not to want what they don''t have.', 'Seneca', 'Letters'),
('Every new beginning comes from some other beginning''s end.', 'Seneca', 'Letters'),
('You act like mortals in all that you fear, and like immortals in all that you desire.', 'Seneca', 'On the Shortness of Life'),
('Expecting is the greatest impediment to living. In anticipation of tomorrow, it loses today.', 'Seneca', 'On the Shortness of Life'),
('It is the power of the mind to be unconquerable.', 'Seneca', 'Letters'),
('The mind that is anxious about future events is miserable.', 'Seneca', 'Letters'),
('Until we have begun to go without them, we fail to realize how unnecessary many things are.', 'Seneca', 'Letters'),
('A sword never kills anybody; it is a tool in the killer''s hand. In the same way, your mind is the tool.', 'Seneca', 'Letters'),
('Brave men rejoice in adversity, just as brave soldiers triumph in war.', 'Seneca', 'Letters'),

-- Others (~20 quotes)
('Well-being is realized by small steps, but is truly no small thing.', 'Zeno of Citium', 'Quoted in Diogenes Laertius'),
('Man conquers the world by conquering himself.', 'Zeno of Citium', 'Quoted in Diogenes Laertius'),
('We have two ears and one mouth, so we should listen more than we say.', 'Zeno of Citium', 'Quoted in Diogenes Laertius'),
('The goal of life is living in agreement with nature.', 'Zeno of Citium', 'Quoted in Diogenes Laertius'),
('Better to trip with the feet than with the tongue.', 'Zeno of Citium', 'Quoted in Diogenes Laertius'),
('Lead me, O Zeus, and thou O Destiny, to wherever your decrees have assigned me.', 'Cleanthes', 'Hymn to Zeus'),
('He who would be free must be a slave to the law.', 'Cleanthes', 'Quoted in Stobaeus'),
('Fate leads the willing and drags along the reluctant.', 'Cleanthes', 'Quoted in Seneca''s Letters'),
('The willing are led by fate, the reluctant dragged.', 'Cleanthes', 'Hymn to Zeus'),
('Could I but purify my life sufficiently, I would not need to mourn what has been lost.', 'Cleanthes', 'Quoted in Stobaeus'),
('In order to become prosperous, one must practice what is good.', 'Musonius Rufus', 'Lectures'),
('If you accomplish something good with hard work, the labor passes quickly, but the good endures.', 'Musonius Rufus', 'Lectures'),
('We begin to lose our hesitation to do immoral things when we lose our hesitation to speak of them.', 'Musonius Rufus', 'Lectures'),
('Eating and drinking without moderation leads to both sickness and vice.', 'Musonius Rufus', 'Lectures'),
('To relax the mind is to lose it.', 'Musonius Rufus', 'Lectures'),
('There could be no justice nor injustice if there were no world at all.', 'Chrysippus', 'Quoted in Plutarch'),
('The universe itself is God and the universal outpouring of its soul.', 'Chrysippus', 'Quoted in Cicero'),
('Living virtuously is equal to living in accordance with one''s experience of the actual course of nature.', 'Chrysippus', 'Quoted in Diogenes Laertius'),
('I do not need a friend who changes when I change and nods when I nod; my shadow does that much better.', 'Cato the Elder', 'Quoted in Plutarch'),
('I would rather do right and get no thanks than do wrong and receive no punishment.', 'Cato the Elder', 'Quoted in Plutarch')
;
